- hosts: all
  tasks:
    - name: Actualiza paquetes del sistema operativo
      apt:
        upgrade: dist
        update_cache: yes
      become: yes
      notify: Reinicia servidor
    - name: Copia los archivos de código
      copy:
        src: myapp
        dest: "{{ ansible_facts.user_dir }}"
      notify: Configura crontab
  handlers:
    - name: Configura crontab
      shell: "crontab {{ ansible_facts.user_dir }}/myapp/Cronfile"
      become: yes
    - name: Reinicia servidor
      reboot:
      become: yes