name: tests
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
jobs:
  actions:
    runs-on: ubuntu-20.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag nies .
    - name: Verifica el formato
      run: docker run nies make check
    - name: Corre pruebas y evalua cobertura
      run: docker run nies make tests
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nepolin/bukeh:latest
